'use client';

import { useMemo, useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ChevronRight, CheckCircle2, Zap, Crown, Lock, ArrowLeft,
  Star, Shield, Clock, Users, Sparkles, Copy, Download,
  Wand2, RefreshCw, Send, Check, Play, Layers, MessageSquare,
  FileText, Video, BarChart2, Lightbulb, Share2, Calculator
} from 'lucide-react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { useAuth } from '@/context/AuthContext';
import { ITEMS } from '@/app/marketplace/marketData';
import { supabase } from '@/lib/supabase';
import * as Lucide from 'lucide-react';
import BrandDealCalculator from '@/components/BrandDealCalculator';

import { getUUIDFromStaticId } from '@/lib/uuidHelper';

const getLucideIcon = (iconName: string) => {
  if (!iconName) return Lucide.Sparkles;
  return (Lucide as any)[iconName] || Lucide.Sparkles;
};

const PLAN_ORDER: Record<string, number>  = { free: 0, silver: 1, gold: 2, platinum: 3 };
const PLAN_COLORS: Record<string, string> = { free: '#10B981', silver: '#94A3B8', gold: '#F59E0B', platinum: '#00F2FE' };
const PLAN_LABELS: Record<string, string> = { free: 'Free Access', silver: 'Silver', gold: 'Gold Tier', platinum: 'Platinum' };

// ── Interactive Generator Presets & Output Builder ─────────────────────────────
const getToolPresets = (toolId: string) => {
  switch (toolId) {
    case 't1':
      return [
        '5 AI Tools That Will Replace Video Editors in 2026',
        'How I Grew from 0 to 100K Subscribers in 6 Months',
        'Stop Making These 3 YouTube Mistakes Right Now'
      ];
    case 't2':
      return [
        'I Tested 100 AI Tools (Shocking Results)',
        'The Secret to 1M Views on Instagram Reels',
        'Why Most Creators Fail in Year 1'
      ];
    case 't3':
      return [
        'How to Get Sponsored by Top Brands Under 10K Followers',
        'The 10-Minute Daily Workflow for Solo Creators',
        'YouTube Automation Blueprint for Beginners'
      ];
    case 't4':
      return [
        'Sponsorship Pitch to Notion for Productive Creators',
        'Brand Collaboration Pitch to Canva for Design Creators',
        'Tech Review Pitch to Sony for Camera Creators'
      ];
    default:
      return [
        'How to Scale Your YouTube Channel in 2026',
        'Viral Storytelling Framework for Short-Form Creators',
        'High-Converting Monetization Blueprint'
      ];
  }
};

const generateMockToolOutput = (toolId: string, topic: string, platform: string, tone: string, niche: string) => {
  const cleanTopic = topic.trim() || 'How to Scale Your Channel';
  
  if (toolId === 't1' || toolId.includes('script')) {
    return `# 🎬 VIRAL VIDEO SCRIPT: "${cleanTopic}"
**Platform:** ${platform} | **Target Niche:** ${niche} | **Tone:** ${tone}
**Estimated Duration:** 60-90s | **Retention Goal:** 82%+

---

## ⚡ 1. THE 5-SECOND VIRAL HOOK (Pick 1 of 3):
• **Formula A (Curiosity Gap):** "Almost every creator is doing ${cleanTopic} wrong... and it’s killing 90% of your channel impressions."
• **Formula B (The Bold Claim):** "If you want to master ${cleanTopic} without wasting 6 months, follow this exact 3-step blueprint."
• **Formula C (The Negative Consequence):** "Stop posting about ${cleanTopic} until you fix this single hidden mistake."

---

## 📖 2. STORYTELLING ARC & PROBLEM:
"Here's the honest truth: most creators struggle with ${cleanTopic} not because they lack passion, but because their retention loop is broken. When viewers click on your video, their brain makes a stay-or-leave decision within the first 4 seconds.

Here is the exact framework top creators use to maintain 80%+ Average View Duration (AVD):"

---

## 🎯 3. THREE CORE ACTIONABLE VALUE POINTS:
1. **The Pattern Interrupt:** Break the visual rhythm every 3 to 4 seconds using B-Roll zoom cuts, on-screen text popups, and sound effects.
2. **The Open Loop:** Tease the most valuable secret in the first 15 seconds, but deliver the final payoff at the 75% mark of the video.
3. **Frictionless Delivery:** Cut out all filler words ("Hey guys welcome back"), jump directly into the thesis, and deliver fast-paced insight.

---

## 🔥 4. HIGH-CONVERTING CALL TO ACTION (CTA):
"If you want the complete step-by-step checklist and Notion template for this workflow, drop a comment with 'BLUEPRINT' below and subscribe for next week's deep dive!"

---
*Generated by Creator Nest AI Intelligence Suite.*`;
  }

  if (toolId === 't2' || toolId.includes('thumbnail')) {
    return `# 🎨 THUMBNAIL CONCEPTS & AI PROMPTS: "${cleanTopic}"
**Target CTR Goal:** 12.5%+ | **Niche:** ${niche}

---

## 🖼️ CONCEPT 1: High-Contrast Curiosity Face + Glow Object
• **Visual Composition:** Extreme close-up of creator face on left with shocked/intense expression. Right side features glowing neon holographic UI element representing ${cleanTopic}.
• **Color Palette:** Deep Obsidian Background (#0B0F15), Neon Cyan (#00F2FE), High-Voltage Amber (#F59E0B).
• **Bold Text Overlay (Max 3 Words):** "DON'T DO THIS!" (Yellow font, heavy drop shadow).
• **Midjourney Prompt:**
\`/imagine prompt: Cinematic 8k photo of a young creator looking intently at a glowing futuristic holographic screen showing data metrics, dramatic rim lighting, neon cyan and orange ambient rim light, high contrast, award winning YouTube thumbnail composition, 16:9 --ar 16:9 --v 6.0 --style raw\`

---

## 🖼️ CONCEPT 2: Split Before vs After Comparison
• **Visual Composition:** Clean split screen. Left side: Dull, gray, red 'X' over old approach. Right side: Ultra-vibrant, glowing green arrow pointing to 10x growth.
• **Bold Text Overlay:** "10X FASTER" or "NEW METHOD".

---
*Generated by Creator Nest AI Intelligence Suite.*`;
  }

  if (toolId === 't3' || toolId.includes('hook')) {
    return `# 🪝 10 VIRAL HOOKS FOR: "${cleanTopic}"
**Platform:** ${platform} | **Category:** ${niche}

1. **The Curiosity Gap:** "I spent 30 days analyzing ${cleanTopic} so you don’t have to make these mistakes."
2. **The Contrarian Angle:** "Everything you've been told about ${cleanTopic} is completely outdated."
3. **The Proof Hook:** "This single strategy generated 450K views on ${cleanTopic} in under 48 hours."
4. **The Direct Warning:** "Stop scrolling if you are trying to learn ${cleanTopic} this year."
5. **The Secret Loophole:** "There is a hidden algorithm trick for ${cleanTopic} that top 1% channels never talk about."
6. **The Story Starter:** "Three months ago, I was completely stuck on ${cleanTopic}. Here's what changed everything."
7. **The Comparison Hook:** "Normal creators do THIS for ${cleanTopic}... but elite creators do THIS instead."
8. **The Challenge Hook:** "I bet you didn't know this 60-second hack for ${cleanTopic}."
9. **The Urgency Hook:** "If you don't implement this for ${cleanTopic} before next month, you're falling behind."
10. **The Numbered Promise:** "Here are 3 tools that will 10x your output on ${cleanTopic} today."

---
*Generated by Creator Nest AI Intelligence Suite.*`;
  }

  if (toolId === 't4' || toolId.includes('pitch')) {
    return `# 💼 SPONSORSHIP PITCH EMAIL: "${cleanTopic}"
**To:** Brand Partnerships Team | **From:** [Your Channel Name]
**Subject Line:** Partnership Idea: [Your Channel] x [Brand Name] (250K+ Highly Targeted Monthly Views)

---

**Hi [Marketing Manager Name / Team],**

I've been a genuine user of [Brand Name] for the past [X months], and our audience of [Niche/Category] creators and viewers frequently asks for recommendations on [Topic/Problem].

I run **[Your Channel Name]**, where we generate **[e.g. 150,000+ monthly views]** with an industry-leading **82% Average View Duration** and high engagement from a tech/creative community.

We are producing an upcoming video titled: **"${cleanTopic}"** scheduled for release next month. 

I'd love to integrate [Brand Name] seamlessly as a dedicated 60-second segment showcasing how [Product Feature] solves [Specific Audience Pain Point].

**Our Audience Snapshot:**
• **Monthly Impressions:** 1.2M+
• **Core Demographics:** 18–34 Tech & Creative Professionals
• **Previous Sponsor Results:** 3.4x average ROAS & 4,500+ direct link clicks

Would you be open to reviewing a 1-page media kit and rough storyboard this week?

Best regards,  
**[Your Name]**  
*Creator & Founder, [Your Channel Link]*  
*Media Kit: creator-nest.in/creators/roster*`;
  }

  return `# 🚀 AI GENERATION: "${cleanTopic}"
**Niche:** ${niche} | **Platform:** ${platform} | **Tone:** ${tone}

## Executive Strategy & Plan:
1. **Core Thesis:** Deliver hyper-focused, retention-tested content around "${cleanTopic}".
2. **Hook Sequence:** Establish immediate viewer intrigue within 3.5 seconds.
3. **Value Layer:** 3 high-impact takeaways structured for maximum viewer saves and shares.
4. **Conversion Mechanism:** Direct CTA driving viewers to subscribe or check the link in bio.

---
*Generated live by Creator Nest AI Intelligence Suite.*`;
};

export default function ToolDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { user } = useAuth();
  const [tool, setTool] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  // Live Interactive Generator States
  const [topicInput, setTopicInput] = useState('');
  const [selectedPlatform, setSelectedPlatform] = useState('YouTube Long-Form');
  const [selectedTone, setSelectedTone] = useState('Viral & Punchy');
  const [selectedNiche, setSelectedNiche] = useState('Tech & AI');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedResult, setGeneratedResult] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let foundTool = null;
    if (typeof window !== 'undefined') {
      const cached = localStorage.getItem('cn_market_items');
      if (cached) {
        const parsed = JSON.parse(cached);
        const localItem = parsed.find((item: any) => String(item.id) === String(id) || getUUIDFromStaticId(String(item.id)) === getUUIDFromStaticId(String(id)));
        if (localItem) {
          foundTool = {
            id: localItem.id,
            type: localItem.item_type,
            title: localItem.title,
            desc: localItem.short_desc,
            short_desc: localItem.short_desc,
            long_desc: localItem.long_desc,
            category: localItem.category,
            icon: getLucideIcon(localItem.icon),
            accent: localItem.accent || '#00F2FE',
            plan: localItem.plan || 'free',
            price: localItem.price || 0,
            rating: localItem.rating || 4.9,
            thumbnail_url: localItem.thumbnail_url,
            file_url: localItem.file_url,
            external_url: localItem.external_url,
            tags: localItem.tags || [],
            details: {
              longDesc: localItem.long_desc || localItem.short_desc,
              features: localItem.features?.features || [],
              usageLimits: localItem.features?.usageLimits || [],
              howItWorks: localItem.features?.howItWorks || []
            }
          };
        }
      }
    }

    if (!foundTool) {
      const staticTool = ITEMS.find((item) => 
        (String(item.id) === String(id) || (item.id === 't-calc' && String(id).includes('calc')) || item.href?.includes(String(id))) && item.type === 'tool'
      );
      if (staticTool) {
        foundTool = staticTool;
      }
    }

    if (foundTool) {
      setTool(foundTool);
      setTopicInput(getToolPresets(String(foundTool.id))[0] || '');
      setLoading(false);
    } else {
      setLoading(true);
    }

    async function fetchTool() {
      try {
        const { data, error } = await supabase
          .from('market_items')
          .select('*')
          .eq('id', getUUIDFromStaticId(id))
          .eq('item_type', 'tool')
          .single();

        if (!error && data) {
          const isJsonFeatures = data.features && typeof data.features === 'object' && !Array.isArray(data.features);
          const mapped = {
            id: data.id,
            type: data.item_type,
            title: data.title,
            desc: data.short_desc,
            short_desc: data.short_desc,
            long_desc: data.long_desc,
            category: data.category,
            icon: getLucideIcon(data.icon),
            accent: data.accent || '#00F2FE',
            plan: data.plan || 'free',
            price: data.price || 0,
            rating: data.rating || 4.9,
            thumbnail_url: data.thumbnail_url,
            file_url: data.file_url,
            external_url: data.external_url,
            tags: data.tags || [],
            details: {
              longDesc: data.long_desc || data.short_desc,
              features: isJsonFeatures ? (data.features.features || []) : (Array.isArray(data.features) ? data.features : []),
              usageLimits: isJsonFeatures ? (data.features.usageLimits || []) : [],
              howItWorks: isJsonFeatures ? (data.features.howItWorks || []) : []
            }
          };
          setTool(mapped);
          setTopicInput(getToolPresets(String(mapped.id))[0] || '');
        }
      } catch (err) {
        console.error("Error background loading tool details", err);
      }
      setLoading(false);
    }
    fetchTool();
  }, [id]);

  const handleRunGenerator = () => {
    setIsGenerating(true);
    setCopied(false);
    setTimeout(() => {
      const output = generateMockToolOutput(
        String(tool?.id || id),
        topicInput,
        selectedPlatform,
        selectedTone,
        selectedNiche
      );
      setGeneratedResult(output);
      setIsGenerating(false);
    }, 700);
  };

  const handleCopyResult = () => {
    if (!generatedResult) return;
    navigator.clipboard.writeText(generatedResult);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadResult = () => {
    if (!generatedResult) return;
    const blob = new Blob([generatedResult], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tool?.title || 'CreatorNest_AI_Output'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading && !tool) {
    return (
      <div className="min-h-screen bg-[#070B11] flex flex-col items-center justify-center text-white">
        <div className="w-10 h-10 border-4 border-primary/30 border-t-primary rounded-full animate-spin mb-4" />
        <p className="text-gray-400 font-bold text-sm">Loading tool workspace...</p>
      </div>
    );
  }

  if (!tool) {
    return (
      <main className="flex min-h-screen flex-col bg-[#070B11] text-white">
        <Navbar />
        <div className="flex-1 flex items-center justify-center p-6">
          <div className="text-center">
            <h1 className="text-2xl font-black text-white mb-4">AI Tool Not Found</h1>
            <Link href="/marketplace" className="text-primary font-bold hover:underline">← Back to Marketplace</Link>
          </div>
        </div>
        <Footer />
      </main>
    );
  }

  const Icon = tool.icon || Lucide.Sparkles;
  const details = tool.details as any;
  const presets = getToolPresets(String(tool.id));
  const isCalculatorTool = String(tool.id) === 't-calc' || String(tool.id) === 'brand-deal-calculator' || String(id).includes('calc');

  // Related tools
  const relatedTools = ITEMS.filter((i) => i.type === 'tool' && String(i.id) !== String(tool.id)).slice(0, 3);

  return (
    <main className="flex min-h-screen flex-col bg-[#070B11] text-white overflow-x-hidden">
      <Navbar />

      {/* ─── Hero Header & Breadcrumbs ─── */}
      <section className="pt-28 pb-6 relative overflow-hidden border-b border-white/10">
        <div className="absolute top-0 left-1/4 w-[500px] h-[300px] rounded-full blur-[140px] pointer-events-none -z-10" style={{ background: `${tool.accent}15` }} />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-xs text-gray-400 mb-6">
            <Link href="/marketplace" className="hover:text-primary transition-colors flex items-center gap-1 font-semibold">
              <ArrowLeft className="w-3.5 h-3.5" /> Marketplace
            </Link>
            <ChevronRight className="w-3 h-3 text-gray-600" />
            <span className="text-gray-400">AI Intelligence Suite</span>
            <ChevronRight className="w-3 h-3 text-gray-600" />
            <span className="text-primary font-bold">{tool.title}</span>
          </div>

          <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
            <div className="flex items-start gap-4">
              <div
                className="w-14 h-14 sm:w-16 sm:h-16 rounded-2xl flex items-center justify-center shrink-0 border shadow-xl"
                style={{ background: `${tool.accent}20`, borderColor: `${tool.accent}40`, color: tool.accent }}
              >
                <Icon className="w-7 h-7 sm:w-8 sm:h-8 drop-shadow-[0_0_8px_currentColor]" />
              </div>
              <div className="space-y-1.5">
                <div className="flex items-center gap-2 flex-wrap">
                  <span
                    className="text-[10px] font-black uppercase tracking-wider px-2.5 py-0.5 rounded-md border"
                    style={{ background: `${PLAN_COLORS[tool.plan]}20`, color: PLAN_COLORS[tool.plan], borderColor: `${PLAN_COLORS[tool.plan]}40` }}
                  >
                    {PLAN_LABELS[tool.plan]}
                  </span>
                  {tool.badge && (
                    <span className="text-[10px] font-black uppercase tracking-wider px-2.5 py-0.5 rounded-md bg-white/10 text-white border border-white/20">
                      {tool.badge}
                    </span>
                  )}
                  <div className="flex items-center gap-1 text-xs text-yellow-400 font-bold ml-1">
                    <Star className="w-3.5 h-3.5 fill-yellow-400" />
                    <span>{tool.rating || '4.9'}</span>
                  </div>
                </div>

                <h1 className="text-2xl sm:text-4xl font-black text-white tracking-tight">{tool.title}</h1>
                <p className="text-gray-300 text-xs sm:text-sm max-w-2xl leading-relaxed">{tool.desc}</p>
              </div>
            </div>

            <div className="flex items-center gap-3 self-stretch sm:self-auto justify-end">
              <a
                href="#live-workspace"
                className="px-6 py-3 rounded-xl font-black text-xs sm:text-sm text-[#05080E] transition-all shadow-lg flex items-center justify-center gap-2"
                style={{ background: `linear-gradient(135deg, ${tool.accent}, #00c8d8)` }}
              >
                <Wand2 className="w-4 h-4" />
                <span>{isCalculatorTool ? 'Open Calculator' : 'Use Tool Now'}</span>
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Main Content & Live Interactive Playground ─── */}
      <section className="py-10 flex-1">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">

          {/* 1. Interactive Live Tool Workspace */}
          {isCalculatorTool ? (
            <div id="live-workspace">
              <BrandDealCalculator />
            </div>
          ) : (
            <div id="live-workspace" className="rounded-3xl border border-primary/30 bg-[#121A26] p-5 sm:p-8 shadow-2xl relative overflow-hidden">
              <div className="absolute top-0 right-0 w-80 h-80 rounded-full blur-[100px] pointer-events-none opacity-25" style={{ background: tool.accent }} />

              <div className="flex items-center justify-between mb-6 pb-4 border-b border-white/10">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-xl bg-primary/20 border border-primary/40 flex items-center justify-center text-primary">
                    <Sparkles className="w-4 h-4" />
                  </div>
                  <div>
                    <h2 className="text-lg sm:text-xl font-black text-white">Live AI Tool Playground</h2>
                    <p className="text-xs text-gray-300">Enter your video topic or select a preset to generate instant creator assets</p>
                  </div>
                </div>

                <span className="text-[11px] font-bold text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full border border-emerald-500/30 flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" /> Live Engine Ready
                </span>
              </div>

              {/* Quick Presets */}
              <div className="mb-6 space-y-2">
                <span className="text-[11px] font-bold text-gray-400 uppercase tracking-wider">Example Topic Ideas:</span>
                <div className="flex flex-wrap gap-2">
                  {presets.map((preset, idx) => (
                    <button
                      key={idx}
                      onClick={() => setTopicInput(preset)}
                      className="text-xs px-3 py-1.5 rounded-xl bg-[#1E2B3D] hover:bg-[#2B3C54] text-slate-200 border border-white/15 transition-all text-left font-medium"
                    >
                      💡 {preset}
                    </button>
                  ))}
                </div>
              </div>

              {/* Form Inputs Grid */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5">
                {/* Platform Selector */}
                <div>
                  <label className="block text-xs font-bold text-gray-300 mb-1.5 uppercase tracking-wider">Target Format</label>
                  <select
                    value={selectedPlatform}
                    onChange={(e) => setSelectedPlatform(e.target.value)}
                    className="w-full bg-[#182333] border border-white/20 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-primary cursor-pointer font-bold"
                  >
                    <option value="YouTube Long-Form">YouTube Long-Form (8-15 min)</option>
                    <option value="Instagram Reel / Short">Instagram Reel / YouTube Short (60s)</option>
                    <option value="Podcast & Discussion">Podcast Episode Outline</option>
                    <option value="Educational Tutorial">Step-by-Step Educational Guide</option>
                  </select>
                </div>

                {/* Tone Selector */}
                <div>
                  <label className="block text-xs font-bold text-gray-300 mb-1.5 uppercase tracking-wider">Tone & Style</label>
                  <select
                    value={selectedTone}
                    onChange={(e) => setSelectedTone(e.target.value)}
                    className="w-full bg-[#182333] border border-white/20 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-primary cursor-pointer font-bold"
                  >
                    <option value="Viral & Punchy">⚡ Viral, Punchy & High-Energy</option>
                    <option value="Educational & In-Depth">🎓 Educational & Practical</option>
                    <option value="Storytelling & Narrative">📖 Narrative Storytelling</option>
                    <option value="Direct Sales & Promo">💼 Sponsor & Brand Pitch</option>
                  </select>
                </div>

                {/* Niche Selector */}
                <div>
                  <label className="block text-xs font-bold text-gray-300 mb-1.5 uppercase tracking-wider">Creator Niche</label>
                  <select
                    value={selectedNiche}
                    onChange={(e) => setSelectedNiche(e.target.value)}
                    className="w-full bg-[#182333] border border-white/20 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-primary cursor-pointer font-bold"
                  >
                    <option value="Tech, AI & Gadgets">Tech, AI & Software</option>
                    <option value="Education & Upskilling">Education & Upskilling</option>
                    <option value="Entertainment & Comedy">Entertainment & Comedy</option>
                    <option value="Finance & Business">Finance & Entrepreneurship</option>
                    <option value="Gaming & Esports">Gaming & Esports</option>
                    <option value="Lifestyle & Fashion">Lifestyle & D2C</option>
                  </select>
                </div>
              </div>

              {/* Prompt / Topic Input */}
              <div className="mb-5">
                <label className="block text-xs font-bold text-gray-300 mb-1.5 uppercase tracking-wider">Video Topic, Title or Brief</label>
                <textarea
                  value={topicInput}
                  onChange={(e) => setTopicInput(e.target.value)}
                  placeholder="e.g., 5 AI Tools that will replace video editors in 2026..."
                  rows={3}
                  className="w-full p-3.5 rounded-2xl bg-[#182333] border border-white/20 text-sm text-white placeholder:text-gray-500 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-inner"
                />
              </div>

              {/* Generate Button */}
              <button
                onClick={handleRunGenerator}
                disabled={isGenerating || !topicInput.trim()}
                className="w-full py-3.5 px-6 rounded-xl font-black text-sm text-[#05080E] transition-all flex items-center justify-center gap-2 shadow-xl hover:opacity-95 active:scale-[0.99] disabled:opacity-50 cursor-pointer"
                style={{ background: `linear-gradient(135deg, ${tool.accent}, #00c8d8)` }}
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>Processing AI Generation...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    <span>Generate Content Now</span>
                  </>
                )}
              </button>

              {/* Generated Output Canvas */}
              <AnimatePresence>
                {generatedResult && (
                  <motion.div
                    initial={{ opacity: 0, y: 15 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mt-6 pt-6 border-t border-white/10"
                  >
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-xs font-black text-primary uppercase tracking-wider flex items-center gap-1.5">
                        <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Generated AI Output
                      </span>

                      <div className="flex items-center gap-2">
                        <button
                          onClick={handleCopyResult}
                          className="px-3 py-1.5 rounded-lg bg-[#1E2B3D] hover:bg-[#2B3C54] text-white text-xs font-bold border border-white/15 flex items-center gap-1.5 transition-all shadow-sm cursor-pointer"
                        >
                          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                          <span>{copied ? 'Copied!' : 'Copy Script'}</span>
                        </button>

                        <button
                          onClick={handleDownloadResult}
                          className="px-3 py-1.5 rounded-lg bg-[#1E2B3D] hover:bg-[#2B3C54] text-white text-xs font-bold border border-white/15 flex items-center gap-1.5 transition-all shadow-sm cursor-pointer"
                        >
                          <Download className="w-3.5 h-3.5 text-primary" />
                          <span>Download .txt</span>
                        </button>
                      </div>
                    </div>

                    <div className="bg-[#0A0F17] rounded-2xl p-5 border border-white/15 text-sm text-gray-200 leading-relaxed font-mono whitespace-pre-wrap max-h-[500px] overflow-y-auto shadow-inner">
                      {generatedResult}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          )}

          {/* 2. Tool Details & Specifications */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            
            {/* Left 2 Cols: Features & How it works */}
            <div className="lg:col-span-2 space-y-8">
              {/* About */}
              {details?.longDesc && (
                <div className="p-6 rounded-2xl bg-[#141E2C] border border-white/15">
                  <h3 className="text-lg font-black text-white mb-3">About This AI Tool</h3>
                  <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-line">{details.longDesc}</p>
                </div>
              )}

              {/* What's Included */}
              {details?.features && details.features.length > 0 && (
                <div>
                  <h3 className="text-lg font-black text-white mb-4">Included Capabilities</h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {details.features.map((f: string, i: number) => (
                      <div key={i} className="flex items-start gap-3 p-4 rounded-xl bg-[#141E2C] border border-white/10">
                        <CheckCircle2 className="w-4 h-4 flex-shrink-0 mt-0.5 text-primary" />
                        <span className="text-xs sm:text-sm text-gray-200 font-medium">{f}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* How it works */}
              {details?.howItWorks && details.howItWorks.length > 0 && (
                <div>
                  <h3 className="text-lg font-black text-white mb-4">How To Use</h3>
                  <div className="space-y-2.5">
                    {details.howItWorks.map((step: string, i: number) => (
                      <div key={i} className="flex items-start gap-3.5 p-3.5 rounded-xl bg-[#141E2C] border border-white/10">
                        <span className="w-6 h-6 rounded-full bg-primary/20 text-primary font-black text-xs flex items-center justify-center shrink-0 border border-primary/30">
                          {i + 1}
                        </span>
                        <span className="text-xs sm:text-sm text-gray-300 leading-relaxed font-medium">{step}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Right 1 Col: Usage Limits & Related Tools */}
            <div className="space-y-6">
              {/* Usage Limits Card */}
              <div className="p-5 rounded-2xl bg-[#141E2C] border border-white/15">
                <h3 className="text-sm font-black text-white uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Shield className="w-4 h-4 text-primary" /> Usage Quota By Tier
                </h3>
                <div className="space-y-2.5">
                  {[
                    { plan: 'Free', limit: 'Unlimited Access' },
                    { plan: 'Silver', limit: 'Unlimited + PDF Export' },
                    { plan: 'Gold', limit: 'Unlimited + Media Kit Sync' },
                    { plan: 'Platinum', limit: 'Unlimited + Agency Review' },
                  ].map((u, i) => (
                    <div key={i} className="flex items-center justify-between p-2.5 rounded-xl bg-[#1E2B3D] border border-white/10 text-xs">
                      <span className="font-bold text-white">{u.plan}</span>
                      <span className="text-gray-300 font-medium">{u.limit}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Related Tools */}
              {relatedTools.length > 0 && (
                <div className="p-5 rounded-2xl bg-[#141E2C] border border-white/15">
                  <h3 className="text-sm font-black text-white uppercase tracking-wider mb-4">Related AI Tools</h3>
                  <div className="space-y-3">
                    {relatedTools.map((rt) => {
                      const RtIcon = rt.icon || Lucide.Sparkles;
                      return (
                        <Link
                          key={rt.id}
                          href={`/marketplace/tool/${rt.id}`}
                          className="flex items-start gap-3 p-3 rounded-xl bg-[#1E2B3D] hover:bg-[#2B3C54] border border-white/10 transition-all group"
                        >
                          <div className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 border" style={{ background: `${rt.accent}20`, borderColor: `${rt.accent}40`, color: rt.accent }}>
                            <RtIcon className="w-4 h-4" />
                          </div>
                          <div className="min-w-0">
                            <p className="text-xs font-bold text-white group-hover:text-primary transition-colors truncate">{rt.title}</p>
                            <p className="text-[10px] text-gray-400 line-clamp-1">{rt.desc}</p>
                          </div>
                        </Link>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>

          </div>

        </div>
      </section>

      <Footer />
    </main>
  );
}
